# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Renato Sugimoto
email: renatoks@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Renato Sugimoto personal blog, where he writes about software development, tutorials, and how-tos.
baseurl: '' # the subpath of your site, e.g. /blog
url: 'https://renatosugimoto.com' # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: renatosugimoto
github_username: renatosugimoto

# Build settings
remote_theme: 'mmistakes/minimal-mistakes@4.24.0'
minimal_mistakes_skin: 'sunrise'
plugins:
  - jekyll-feed
  - jekyll-include-cache

defaults:
  # _posts
  - scope:
      path: ''
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      toc: true
      # related: true
author:
  # name: "Renato Sugimoto"
  avatar: '/assets/images/bio-photo.jpg'
  bio: 'System Architect \| DevOps \| Developer \| Constant learner' # Note: Markdown is allowed
  location: 'Tokyo'
  links:
    - label: 'X'
      icon: 'fa-brands fa-x-twitter'
      url: 'https://x.com/renatosugimoto'
    - label: 'GitHub'
      icon: 'fa-brands fa-github'
      url: 'https://github.com/renatosugimoto'
    - label: 'LinkedIn'
      icon: 'fa-brands fa-linkedin'
      url: 'https://www.linkedin.com/in/renatosugimoto/'
    - label: 'Dev'
      icon: 'fa-brands fa-dev'
      url: 'https://dev.to/renatosugimoto'
    - label: 'HackerNoon'
      icon: 'fa-solid fa-link'
      url: 'https://hackernoon.com/u/renatosugimoto'

social:
  links:
    - 'https://twitter.com/RenatoSugimoto'
    - 'https://www.linkedin.com/in/RenatoSugimoto'

analytics:
  provider: 'google-gtag'
  google:
    tracking_id: 'G-142E8GCRQR'
    anonymize_ip: true

timezone: Asia/Tokyo

repository: renatosugimoto/renatosugimoto.github.io

comments:
  provider: 'utterances'
  utterances:
    theme: 'github-light' # "github-dark"
    issue_term: 'pathname'

tag_archive:
  type: liquid
  path: /tags/
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
